import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Free Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/create/new" passHref>
          <StyledAnchor>Create your first Survey</StyledAnchor>
        </Link>
      </main>
    </div>
  );
}
const StyledAnchor = styled.a`
  all: unset;
  border: 1px solid black;
  border-radius: 0.2em;
  background-color: #ddd;
  padding: 0.2em;
  &:hover{
    cursor: pointer;
  }
`;
